"""
Domain-specific analysis modules for the LocalData MCP pipeline.

This package contains specialized analysis domains that integrate with the
core pipeline framework, each implementing specific analytical capabilities
using sklearn-compatible transformers.

Available domains:
- statistical_analysis: Comprehensive statistical analysis tools
- regression_modeling: Comprehensive regression analysis and modeling capabilities
- pattern_recognition: Advanced clustering, dimensionality reduction, and anomaly detection
- time_series: Time series analysis, forecasting, and temporal pattern detection
- optimization: Optimization and operations research capabilities
- business_intelligence: RFM, cohort analysis, A/B testing, CLV
- sampling_estimation: Bootstrap, Bayesian estimation, Monte Carlo simulation
- geospatial_analysis: Spatial analysis, routing, clustering
"""

from .business_intelligence import (  # Core transformers; Pipeline; High-level functions; Result classes; Enums
    ABTestAnalyzer,
    ABTestResult,
    AttributionAnalyzer,
    AttributionModel,
    AttributionResult,
    BusinessIntelligencePipeline,
    CLVCalculator,
    CLVResult,
    CohortAnalysisResult,
    CohortAnalysisTransformer,
    ExperimentStatus,
    FunnelAnalysisResult,
    FunnelAnalyzer,
    PowerAnalysisTransformer,
    RFMAnalysisTransformer,
    RFMResult,
    analyze_attribution,
    analyze_funnel,
    analyze_rfm,
    calculate_clv,
    enhanced_ab_test,
    perform_ab_test,
    perform_cohort_analysis,
)
from .geospatial_analysis import (  # Core transformers; Spatial data structures; Analysis engines; High-level functions; Result classes; Pipeline; Enums
    AccessibilityAnalyzer,
    AccessibilityResult,
    GeospatialAnalysisPipeline,
    GeospatialDependencyChecker,
    GeospatialLibrary,
    IsochroneGenerator,
    IsochroneResult,
    NetworkAnalysisType,
    NetworkRouter,
    OverlayOperation,
    OverlayResult,
    RouteResult,
    SpatialAggregator,
    SpatialAutocorrelationTransformer,
    SpatialCoordinateTransformer,
    SpatialDataFrame,
    SpatialDistanceTransformer,
    SpatialGeometryTransformer,
    SpatialInterpolationTransformer,
    SpatialJoinEngine,
    SpatialJoinResult,
    SpatialJoinTransformer,
    SpatialJoinType,
    SpatialNetwork,
    SpatialNetworkTransformer,
    SpatialOverlayEngine,
    SpatialOverlayTransformer,
    SpatialPoint,
    aggregate_points_in_polygons,
    analyze_accessibility,
    analyze_spatial_autocorrelation,
    calculate_spatial_distance,
    generate_service_isochrones,
    optimize_route,
    optimize_routes,
    perform_spatial_clustering,
    perform_spatial_join,
    perform_spatial_overlay,
)
from .optimization import (  # Core transformers; High-level functions; Result classes
    AssignmentResult,
    AssignmentSolver,
    ConstrainedOptimizer,
    ConstrainedOptResult,
    LinearProgrammingSolver,
    LinearProgramResult,
    NetworkAnalysisResult,
    NetworkAnalyzer,
    OptimizationResult,
    analyze_network,
    optimize_constrained,
    solve_assignment_problem,
    solve_linear_program,
)
from .pattern_recognition import (  # Core transformers; High-level functions; Result classes
    AnomalyDetectionResult,
    AnomalyDetectionTransformer,
    ClusteringResult,
    ClusteringTransformer,
    DimensionalityReductionResult,
    DimensionalityReductionTransformer,
    PatternEvaluationResult,
    PatternEvaluationTransformer,
    detect_anomalies,
    evaluate_patterns,
    perform_clustering,
    reduce_dimensions,
)
from .regression_modeling import (  # Core transformers; Pipeline; High-level functions; Result classes
    FeatureSelectionTransformer,
    LinearRegressionTransformer,
    LogisticRegressionTransformer,
    PolynomialRegressionTransformer,
    RegressionModelingPipeline,
    RegressionModelResult,
    RegularizedRegressionTransformer,
    ResidualAnalysisResult,
    ResidualAnalysisTransformer,
    analyze_residuals,
    evaluate_model_performance,
    fit_regression_model,
    select_features,
)
from .sampling_estimation import (  # Core transformers; High-level functions; Result classes
    BayesianEstimationTransformer,
    BayesianResult,
    BootstrapResult,
    BootstrapTransformer,
    MonteCarloResult,
    MonteCarloTransformer,
    SamplingResult,
    SamplingTransformer,
    bayesian_estimate,
    bootstrap_statistic,
    generate_sample,
    monte_carlo_simulate,
)
from .statistical_analysis import (
    ANOVAAnalysisTransformer,
    ExperimentalDesignTransformer,
    HypothesisTestingTransformer,
    NonParametricTestTransformer,
    analyze_experiment_design,
    calculate_effect_sizes,
    perform_anova,
    run_hypothesis_test,
)
from .time_series import (
    AnomalyDetectionResult as TimeSeriesAnomalyDetectionResult,  # Core transformers; High-level functions; Result classes
)
from .time_series import (
    AnomalyDetector,
    ARIMAForecaster,
    BasicAnalysisResult,
    BasicTimeSeriesAnalyzer,
    ChangePointDetector,
    ChangePointResult,
    ExponentialSmoothingForecaster,
    ForecastResult,
    MultivariateAnalyzer,
    TimeSeriesAnalyzer,
    TimeSeriesResult,
    analyze_multivariate_time_series,
    analyze_time_series_basic,
    detect_change_points,
    detect_time_series_anomalies,
    forecast_arima,
    forecast_exponential_smoothing,
)

__all__ = [
    # Statistical Analysis Domain
    "HypothesisTestingTransformer",
    "ANOVAAnalysisTransformer",
    "NonParametricTestTransformer",
    "ExperimentalDesignTransformer",
    "run_hypothesis_test",
    "perform_anova",
    "analyze_experiment_design",
    "calculate_effect_sizes",
    # Regression Modeling Domain
    "LinearRegressionTransformer",
    "RegularizedRegressionTransformer",
    "LogisticRegressionTransformer",
    "PolynomialRegressionTransformer",
    "ResidualAnalysisTransformer",
    "FeatureSelectionTransformer",
    "RegressionModelingPipeline",
    "fit_regression_model",
    "evaluate_model_performance",
    "analyze_residuals",
    "select_features",
    "RegressionModelResult",
    "ResidualAnalysisResult",
    # Pattern Recognition Domain
    "ClusteringTransformer",
    "DimensionalityReductionTransformer",
    "AnomalyDetectionTransformer",
    "PatternEvaluationTransformer",
    "perform_clustering",
    "reduce_dimensions",
    "detect_anomalies",
    "evaluate_patterns",
    "ClusteringResult",
    "DimensionalityReductionResult",
    "AnomalyDetectionResult",
    "PatternEvaluationResult",
    # Time Series Domain
    "TimeSeriesAnalyzer",
    "BasicTimeSeriesAnalyzer",
    "ARIMAForecaster",
    "ExponentialSmoothingForecaster",
    "AnomalyDetector",
    "ChangePointDetector",
    "MultivariateAnalyzer",
    "analyze_time_series_basic",
    "forecast_arima",
    "forecast_exponential_smoothing",
    "detect_time_series_anomalies",
    "detect_change_points",
    "analyze_multivariate_time_series",
    "TimeSeriesResult",
    "BasicAnalysisResult",
    "ForecastResult",
    "TimeSeriesAnomalyDetectionResult",
    "ChangePointResult",
    # Optimization Domain
    "LinearProgrammingSolver",
    "ConstrainedOptimizer",
    "NetworkAnalyzer",
    "AssignmentSolver",
    "solve_linear_program",
    "optimize_constrained",
    "analyze_network",
    "solve_assignment_problem",
    "OptimizationResult",
    "LinearProgramResult",
    "ConstrainedOptResult",
    "NetworkAnalysisResult",
    "AssignmentResult",
    # Business Intelligence Domain
    "RFMAnalysisTransformer",
    "CohortAnalysisTransformer",
    "CLVCalculator",
    "ABTestAnalyzer",
    "PowerAnalysisTransformer",
    "AttributionAnalyzer",
    "FunnelAnalyzer",
    "BusinessIntelligencePipeline",
    "analyze_rfm",
    "perform_cohort_analysis",
    "calculate_clv",
    "perform_ab_test",
    "analyze_attribution",
    "analyze_funnel",
    "enhanced_ab_test",
    "RFMResult",
    "CohortAnalysisResult",
    "CLVResult",
    "ABTestResult",
    "AttributionResult",
    "FunnelAnalysisResult",
    "AttributionModel",
    "ExperimentStatus",
    # Sampling & Estimation Domain
    "BootstrapTransformer",
    "BayesianEstimationTransformer",
    "MonteCarloTransformer",
    "SamplingTransformer",
    "bootstrap_statistic",
    "bayesian_estimate",
    "monte_carlo_simulate",
    "generate_sample",
    "BootstrapResult",
    "BayesianResult",
    "MonteCarloResult",
    "SamplingResult",
    # Geospatial Analysis Domain
    "GeospatialDependencyChecker",
    "SpatialCoordinateTransformer",
    "SpatialDistanceTransformer",
    "SpatialGeometryTransformer",
    "SpatialAutocorrelationTransformer",
    "SpatialInterpolationTransformer",
    "SpatialJoinTransformer",
    "SpatialOverlayTransformer",
    "SpatialNetworkTransformer",
    "SpatialPoint",
    "SpatialDataFrame",
    "SpatialJoinEngine",
    "SpatialOverlayEngine",
    "SpatialAggregator",
    "SpatialNetwork",
    "NetworkRouter",
    "AccessibilityAnalyzer",
    "IsochroneGenerator",
    "analyze_spatial_autocorrelation",
    "perform_spatial_clustering",
    "calculate_spatial_distance",
    "optimize_route",
    "optimize_routes",
    "analyze_accessibility",
    "generate_service_isochrones",
    "perform_spatial_join",
    "perform_spatial_overlay",
    "aggregate_points_in_polygons",
    "SpatialJoinResult",
    "OverlayResult",
    "RouteResult",
    "AccessibilityResult",
    "IsochroneResult",
    "GeospatialAnalysisPipeline",
    "GeospatialLibrary",
    "SpatialJoinType",
    "OverlayOperation",
    "NetworkAnalysisType",
]
