name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. Step one
        2. Step two
        3. Step three
        4. See error
    validations:
      required: true

  - type: dropdown
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you running?
      options:
        - Python 3.8
        - Python 3.9
        - Python 3.10
        - Python 3.11
        - Python 3.12
        - Other (please specify in description)
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux (Ubuntu)
        - Linux (other)
        - Other (please specify in description)
    validations:
      required: true

  - type: textarea
    id: package-version
    attributes:
      label: Package Version
      description: What version of localdata-mcp are you using?
      placeholder: "Run: pip show localdata-mcp"
    validations:
      required: true

  - type: textarea
    id: database-info
    attributes:
      label: Database Information
      description: What type of database are you connecting to?
      placeholder: |
        - Database type (SQLite, PostgreSQL, MySQL, etc.)
        - Database version (if applicable)
        - Connection method (file path, connection string, etc.)

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      description: Please copy and paste any relevant error messages or logs
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here