"""Oracle integration tests via MCP tool interface.

Requires a running Oracle Free instance. Start via Docker:

    docker run -e ORACLE_PASSWORD=testpass -e APP_USER=testuser \
        -e APP_USER_PASSWORD=testpass -p 11521:1521 -d gvenzl/oracle-free:slim
"""

import os

import pytest

from .mcp_test_client import call_tool

ORACLE_URL = os.environ.get(
    "TEST_ORACLE_URL",
    "oracle+oracledb://testuser:testpass@localhost:11521/?service_name=FREEPDB1",
)


def _oracle_available():
    try:
        import oracledb

        conn = oracledb.connect(
            user="testuser",
            password="testpass",
            dsn="localhost:11521/FREEPDB1",
        )
        conn.close()
        return True
    except Exception:
        return False


pytestmark = [
    pytest.mark.integration,
    pytest.mark.oracle,
    pytest.mark.skipif(not _oracle_available(), reason="Oracle not available"),
]


@pytest.fixture(scope="module", autouse=True)
def setup_oracle_data():
    """Create a test_data table with 100 rows in the Oracle instance."""
    import oracledb

    conn = oracledb.connect(
        user="testuser",
        password="testpass",
        dsn="localhost:11521/FREEPDB1",
    )
    cursor = conn.cursor()
    cursor.execute("""
        BEGIN
            EXECUTE IMMEDIATE 'DROP TABLE test_data';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -942 THEN RAISE; END IF;
        END;
        """)
    cursor.execute("""
        CREATE TABLE test_data (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR2(100),
            email VARCHAR2(200),
            amount NUMBER(10,2),
            category VARCHAR2(50),
            score FLOAT,
            is_active NUMBER(1),
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """)
    categories = ["A", "B", "C"]
    for i in range(100):
        cursor.execute(
            "INSERT INTO test_data "
            "(name, email, amount, category, score, is_active) "
            "VALUES (:n, :e, :a, :c, :s, :active)",
            {
                "n": f"user_{i}",
                "e": f"user_{i}@test.com",
                "a": float(i * 1.5),
                "c": categories[i % 3],
                "s": float(i % 100) / 100.0,
                "active": i % 2,
            },
        )
    conn.commit()
    cursor.close()
    conn.close()
    yield
    conn = oracledb.connect(
        user="testuser",
        password="testpass",
        dsn="localhost:11521/FREEPDB1",
    )
    cursor = conn.cursor()
    cursor.execute("""
        BEGIN
            EXECUTE IMMEDIATE 'DROP TABLE test_data';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -942 THEN RAISE; END IF;
        END;
        """)
    conn.commit()
    cursor.close()
    conn.close()


def _connect(name):
    """Connect to Oracle via MCP and assert success."""
    result = call_tool(
        "connect_database",
        {"name": name, "db_type": "oracle", "conn_string": ORACLE_URL},
    )
    assert "error" not in str(result).lower(), f"Connection failed: {result}"


# ---------------------------------------------------------------------------
# Connection tests
# ---------------------------------------------------------------------------


class TestOracleConnection:
    def test_connect_oracle(self):
        _connect("ora_conn")
        try:
            result = call_tool(
                "execute_query",
                {"name": "ora_conn", "query": "SELECT 1 AS ok FROM DUAL"},
            )
            assert "1" in str(result), f"Connection not usable: {result}"
        finally:
            call_tool("disconnect_database", {"name": "ora_conn"})

    def test_list_shows_oracle(self):
        _connect("ora_ls")
        try:
            result = call_tool("list_databases", {})
            assert "ora_ls" in str(
                result
            ), f"ora_ls not in list_databases after connect: {result}"
        finally:
            call_tool("disconnect_database", {"name": "ora_ls"})

    def test_disconnect(self):
        _connect("ora_dc")
        call_tool("disconnect_database", {"name": "ora_dc"})
        result = call_tool("list_databases", {})
        assert "ora_dc" not in str(
            result
        ), f"ora_dc still listed after disconnect: {result}"

    def test_duplicate_connect_rejected(self):
        _connect("ora_dup")
        try:
            result = call_tool(
                "connect_database",
                {"name": "ora_dup", "db_type": "oracle", "conn_string": ORACLE_URL},
            )
            result_str = str(result)
            assert (
                "already" in result_str.lower() or "error" in result_str.lower()
            ), f"Expected duplicate-name error: {result_str}"
        finally:
            call_tool("disconnect_database", {"name": "ora_dup"})


# ---------------------------------------------------------------------------
# Query tests
# ---------------------------------------------------------------------------


class TestOracleQueries:
    def test_select(self):
        _connect("ora_sel")
        try:
            result = call_tool(
                "execute_query",
                {
                    "name": "ora_sel",
                    "query": ("SELECT name, email FROM test_data WHERE ROWNUM <= 10"),
                },
            )
            result_str = str(result)
            assert "user_" in result_str, f"Expected user rows: {result_str}"
        finally:
            call_tool("disconnect_database", {"name": "ora_sel"})

    def test_where_filter(self):
        _connect("ora_whr")
        try:
            result = call_tool(
                "execute_query",
                {
                    "name": "ora_whr",
                    "query": (
                        "SELECT name, email, category "
                        "FROM test_data WHERE category = 'A'"
                    ),
                },
            )
            result_str = str(result)
            assert "user_" in result_str, f"Expected user rows: {result_str}"
        finally:
            call_tool("disconnect_database", {"name": "ora_whr"})

    def test_aggregation(self):
        _connect("ora_agg")
        try:
            result = call_tool(
                "execute_query",
                {
                    "name": "ora_agg",
                    "query": (
                        "SELECT category, COUNT(*) AS cnt, "
                        "SUM(amount) AS total "
                        "FROM test_data GROUP BY category"
                    ),
                },
            )
            result_str = str(result)
            assert (
                "category" in result_str.lower() or "A" in result_str
            ), f"Aggregation result missing expected data: {result_str}"
        finally:
            call_tool("disconnect_database", {"name": "ora_agg"})

    def test_join(self):
        _connect("ora_join")
        try:
            result = call_tool(
                "execute_query",
                {
                    "name": "ora_join",
                    "query": (
                        "SELECT a.name, b.category "
                        "FROM test_data a "
                        "INNER JOIN test_data b ON a.id = b.id "
                        "WHERE a.category = 'A' AND ROWNUM <= 5"
                    ),
                },
            )
            result_str = str(result)
            assert "error" not in result_str.lower(), f"Join query failed: {result_str}"
        finally:
            call_tool("disconnect_database", {"name": "ora_join"})


# ---------------------------------------------------------------------------
# Schema introspection tests
# ---------------------------------------------------------------------------


class TestOracleSchemaIntrospection:
    def test_describe_database(self):
        _connect("ora_desc")
        try:
            result = call_tool("describe_database", {"name": "ora_desc"})
            result_str = str(result).lower()
            assert (
                "test_data" in result_str
            ), f"test_data not found in describe_database: {result_str}"
        finally:
            call_tool("disconnect_database", {"name": "ora_desc"})

    def test_describe_table(self):
        _connect("ora_dtbl")
        try:
            result = call_tool(
                "describe_table",
                {"name": "ora_dtbl", "table_name": "test_data"},
            )
            result_str = str(result).lower()
            assert (
                "name" in result_str
            ), f"Column 'name' not found in describe_table: {result_str}"
        finally:
            call_tool("disconnect_database", {"name": "ora_dtbl"})


# ---------------------------------------------------------------------------
# Error handling tests
# ---------------------------------------------------------------------------


class TestOracleErrors:
    def test_bad_url(self):
        result = call_tool(
            "connect_database",
            {
                "name": "ora_bad",
                "db_type": "oracle",
                "conn_string": (
                    "oracle+oracledb://baduser:badpass@localhost:19999"
                    "/?service_name=NOPE"
                ),
            },
        )
        try:
            result_str = str(result)
            assert (
                "error" in result_str.lower() or "fail" in result_str.lower()
            ), f"Expected error for bad URL: {result_str}"
        finally:
            try:
                call_tool("disconnect_database", {"name": "ora_bad"})
            except Exception:
                pass

    def test_disconnect_nonexistent(self):
        result = call_tool("disconnect_database", {"name": "ora_nonexist_xyz"})
        result_str = str(result)
        assert (
            "error" in result_str.lower() or "not" in result_str.lower()
        ), f"Expected error for nonexistent disconnect: {result_str}"

    def test_query_nonexistent_connection(self):
        result = call_tool(
            "execute_query",
            {"name": "ora_nonexist_xyz", "query": "SELECT 1 FROM DUAL"},
        )
        result_str = str(result)
        assert (
            "error" in result_str.lower() or "not" in result_str.lower()
        ), f"Expected error for nonexistent query: {result_str}"
