name: Publish to PyPI

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for PyPI trusted publishing
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Extract version from tag
      run: |
        if [[ $GITHUB_REF == refs/tags/v* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        else
          echo "No version tag found"
          exit 1
        fi
    
    - name: Update version in pyproject.toml
      run: |
        sed -i "s/^version = .*/version = \"$VERSION\"/" pyproject.toml
        echo "Updated version to $VERSION"
        grep "version = " pyproject.toml
    
    - name: Build package
      run: |
        python -m build
    
    - name: Check package
      run: |
        python -m twine check dist/*
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
    
    - name: Verify publication
      run: |
        echo "Package published to PyPI!"
        echo "Version: $VERSION"
        echo "Check at: https://pypi.org/project/localdata-mcp/$VERSION/"